name: shibuya_app
description: A new Flutter project for Shibuya tourism
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.32.0
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  provider: ^6.1.1
  table_calendar: ^3.0.9
  cached_network_image: ^3.3.0
  intl: ^0.18.1
  google_maps_flutter: ^2.10.0
  geolocator: ^13.0.2
  envied: ^1.0.0
  url_launcher: ^6.3.1
  flutter_polyline_points: ^2.1.0
  image_picker: ^1.1.2
  firebase_storage: ^11.6.5
  camera: ^0.11.0+2
  path_provider: ^2.1.5
  path: ^1.9.0
  google_sign_in: ^6.2.2
  google_places_flutter: ^2.0.9
  flutter_google_maps_webservices: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.13
  envied_generator: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/