name: shibuya_app
description: A new Flutter project for Shibuya tourism
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.9.0
  firebase_storage: ^12.3.7
  geolocator: ^13.0.2
  camera: ^0.11.0+2
  firebase_auth: ^5.3.4
  google_maps_flutter: ^2.10.0
  cloud_firestore: ^5.6.0
  sign_in_button: ^3.2.0
  google_sign_in: ^6.2.2
  google_places_flutter: ^2.0.9
  geocoding: ^3.0.0
  google_maps_webservice: ^0.0.7
  flutter_polyline_points: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  envied_generator: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/